config/routes.rb
Internship::Application.routes.draw do

  resources :interns do
    member do
      get 'applyfor'
      get 'applylist'
      get 'clone'
    end
  end
  devise_for :users
  root 'interns#index'

end

app/models/intern.rb
class Intern < ActiveRecord::Base
  has_many :requests
  has_many :users, through: :requests
end

app/models/request.rb
class Request < ActiveRecord::Base
  belongs_to :user
  belongs_to :intern
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable
  #validates :name, :classlevel, :sn, :tel, presence: true, on: :update
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :requests
  has_many :interns, through: :requests

  GENDER=[['男','1'],['女','0']]

  def already_applied(intern_id)
    self.requests.find_by_intern_id(intern_id).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :tel, :address, :reason, :classlevel, :sn) }
  end
end

app/controllers/interns_controller.rb
class InternsController < ApplicationController
  before_action :set_intern, only: [:show, :edit, :update, :destroy, :applyfor, :applylist, :clone]
  before_action :authenticate_user!
  before_action :user_ready, except: [:index]

  respond_to :html

  def index
    @interns = Intern.all.order("endtime desc")
    respond_with(@interns)
  end

  def show
    respond_with(@intern)
  end

  def new
    @intern = Intern.new
    respond_with(@intern)
  end

  def edit
  end

  def create
    @intern = Intern.new(intern_params)
    @intern.save
    respond_with(@intern, location: interns_url)
  end

  def update
    @intern.update(intern_params)
    respond_with(@intern, location: interns_url)
  end

  def destroy
    @intern.destroy
    respond_with(@intern)
  end

  def applyfor
    if current_user.already_applied(@intern)
      redirect_to interns_url, flash: { alert: "#{@intern.title} 之實習已申請過囉!" }
    else
      current_user.requests.create(intern: @intern)
      respond_with @intern do |format|
        format.html {redirect_to interns_url, flash: { notice: "#{@intern.title} 之實習已登記完成" } }
      end
    end
  end

  def applylist
    if current_user.admin
      @interns = @intern.users
      respond_with(@interns)
    else
      redirect_to interns_url
    end
  end

  def clone
    if current_user.admin
      @clone_intern = @intern.dup
      @clone_intern.title = "#{@clone_intern.title}_new_#{Date.today}" 
      if @clone_intern.save
        redirect_to interns_url, notice: "#{@intern.title} 之實習複製成功"
      else
        redirect_to interns_url, alert: "#{@intern.title} 之實習複製失敗"
      end
    else
      redirect_to interns_url
    end
  end

  private
    def set_intern
      @intern = Intern.find(params[:id])
    end

    def intern_params
      params.require(:intern).permit(:title, :starttime, :endtime, :description, :url)
    end

    def user_ready
      unless current_user.name.present?
        redirect_to edit_user_registration_path, flash: { alert: "請先將必填的資料填寫完整喔!" }
      end
    end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @requests = Request.all
    respond_with(@requests)
  end

  def show
    respond_with(@request)
  end

  def new
    @request = Request.new
    respond_with(@request)
  end

  def edit
  end

  def create
    @request = Request.new(request_params)
    @request.save
    respond_with(@request)
  end

  def update
    @request.update(request_params)
    respond_with(@request)
  end

  def destroy
    @request.destroy
    respond_with(@request)
  end

  private
    def set_request
      @request = Request.find(params[:id])
    end

    def request_params
      params.require(:request).permit(:intern_id, :user_id, :request_date, :mark)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/interns_helper.rb
module InternsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/interns/_form.html.erb
<%= form_for(@intern, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @intern.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@intern.errors.count, "error") %> prohibited this intern from being saved:</h4>

      <ul>
      <% @intern.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "實習單位", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "公告日期", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :starttime, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "截止日期", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.date_select :endtime, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "實習說明", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.cktext_area :description, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label "參考網址", :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "送出", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/interns/applylist.html.erb
<div class="page-header">
  <%= link_to interns_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @intern, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>實習申請清單</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>班級</th>
            <th>學號</th>
            <th>姓名</th>
            <th>性別</th>
            <th>電話</th>
            <th>Email</th>
            <th>住址</th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @interns) do |intern| %>
            <td><%= intern.classlevel %></td>
            <td><%= intern.sn %></td>
            <td><%= intern.name %></td>
            <td><%= intern.gender %></td>
            <td><%= intern.tel %></td>
            <td><%= intern.email %></td>
            <td><%= intern.address %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/interns/edit.html.erb
<div class="page-header">
  <%= link_to interns_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @intern, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>修改實習內容</h1>
</div>

<%= render 'form' %>

app/views/interns/index.html.erb
<div class="page-header">
<% if current_user.admin %>
  <%= link_to new_intern_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    新增實習
  <% end %>
<% end %>
  <h1>實習資訊</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>實習單位</th>
            <th>公告日期</th>
            <th>截止日期</th>
            <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @interns) do |intern| %>
            <td><%= link_to intern.title, intern %></td>
            <td><%= intern.starttime %></td>
            <td><%= intern.endtime %></td>
            <% if intern.endtime.past? %>
            <td>已截止</td>
            <% else %>
            <td><%= link_to '我要申請', intern, class: "btn btn-default" %></td>
            <% end %>
        <% if current_user.admin %>
        <td><%= link_to '名單', applylist_intern_path(intern), class: "btn btn-default" %></td>
        <td><%= link_to '修改', edit_intern_path(intern) , class: "btn btn-default"  %></td>
        <td><%= link_to '刪除', intern, method: :delete, data: { confirm: '確定要刪除?' } , class: "btn btn-default"  %></td>
        <td><%= link_to '複製', clone_intern_path(intern), class: "btn btn-default" %></td>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/interns/new.html.erb
<div class="page-header">
  <%= link_to interns_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>新增實習</h1>
</div>

<%= render 'form' %>

app/views/interns/show.html.erb
<div class="page-header">
<% if current_user.admin %>
  <%= link_to interns_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_intern_path(@intern), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
<% end -%>
  <h1>實習資訊</h1>
</div>

<dl class="dl-horizontal">
  <dt>實習單位</dt>
  <dd><%= @intern.title %></dd>

  <dt>公告日期</dt>
  <dd><%= @intern.starttime %></dd>

  <dt>截止日期</dt>
  <dd><%= @intern.endtime %></dd>

  <dt>實習說明</dt>
  <dd><%= @intern.description.html_safe %></dd>

  <dt>參考網址</dt>
  <dd><%= link_to @intern.url, @intern.url %></dd>

  <dt>申請?</dt>
  <dd><%= link_to "我要申請", applyfor_intern_path(@intern), class: "btn btn-primary" %></dd>

</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>實習報名</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "樹科大行銷系實習報名系統", root_path, :class => "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
      <%= render_list :class => "nav navbar-nav" do |li|
         li << link_to("Home", root_path)
         li << link_to("資料更新", edit_user_registration_path)
      end %>
      <%= render_list :class => "nav navbar-nav navbar-right" do |li|
         li << link_to("登出", destroy_user_session_path, method: :delete) 
      end %>
      </div>
    </div>
  </nav>
  <div class="container">
<!--     <% flash.each do |name, msg| %>
      <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %> -->
    <%= notice_message %>

    <%= yield %>
  </div>
</body>
</html>

app/views/requests/_form.html.erb
<%= form_for(@request, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @request.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@request.errors.count, "error") %> prohibited this request from being saved:</h4>

      <ul>
      <% @request.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :intern_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :intern_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_id, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :user_id, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :request_date, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_select :request_date, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :mark, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.check_box :mark, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/requests/edit.html.erb
<div class="page-header">
  <%= link_to requests_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @request, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing request</h1>
</div>

<%= render 'form' %>

app/views/requests/index.html.erb
<div class="page-header">
  <%= link_to new_request_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Request
  <% end %>
  <h1>Listing requests</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Intern</th>
            <th>User</th>
            <th>Request date</th>
            <th>Mark</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @requests) do |request| %>
            <td><%= request.intern_id %></td>
            <td><%= request.user_id %></td>
            <td><%= request.request_date %></td>
            <td><%= request.mark %></td>
            <td><%= link_to 'Show', request %></td>
        <td><%= link_to 'Edit', edit_request_path(request) %></td>
        <td><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/requests/new.html.erb
<div class="page-header">
  <%= link_to requests_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New request</h1>
</div>

<%= render 'form' %>

app/views/requests/show.html.erb
<div class="page-header">
  <%= link_to requests_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_request_path(@request), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show request</h1>
</div>

<dl class="dl-horizontal">
  <dt>Intern:</dt>
  <dd><%= @request.intern_id %></dd>

  <dt>User:</dt>
  <dd><%= @request.user_id %></dd>

  <dt>Request date:</dt>
  <dd><%= @request.request_date %></dd>

  <dt>Mark:</dt>
  <dd><%= @request.mark %></dd>

</dl>

app/views/welcome/index.html.erb
<div class="page-header">
  <h1>行銷系春天藝術節實習報名</h1>
</div>
<p>
<% if !current_user.name.present? || current_user.name.empty? %>
<%= link_to "我要報名", edit_user_registration_path, class: "btn btn-success" %>
<% else %>
<%= link_to "更新報名資料", edit_user_registration_path, class: "btn btn-default" %>
<% end -%>
<p>
<%= image_tag "http://www.ksaf.com.tw/files/program/冒險英雄.jpg", size: "900x417" %>
</p>